version: 5.4.0
# was - 5.3.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: .\appveyor.ps1
build:
  project: src/storage.sln
  verbosity: minimal
test_script:
- ps: dotnet test .\src\Storage.Net.Tests\ -c debug
artifacts:
- path: src/**/*.nupkg
deploy:
- provider: Environment
  name: aloneguid NuGet