version: {build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
environment:
  NUGET_DEPLOY: 0
before_build:
- ps: .\appveyor.ps1
build:
  project: src/storage.sln
  verbosity: minimal
test_script:
- ps: dotnet test .\src\Storage.Net.Tests\ -c debug
artifacts:
- path: src/**/*.nupkg
deploy:
- provider: Environment
  name: aloneguid NuGet
  on:
    NUGET_DEPLOY: 1