version: "{build}"
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- ps: .\appveyor.ps1
build:
  project: src/storage.sln
  verbosity: minimal
test_script:
- ps: dotnet test .\src\Storage.Net.Tests\ -c release
artifacts:
- path: src/**/*.nupkg
deploy: off