trigger:
  batch: true
  branches:
    include:
      - master
      - v7
  paths:
    exclude:
      - README.md
      - /doc/**/*

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - README.md
      - /doc/**/*

variables:
  - group: 'External Resources'

stages:
- stage: Build
  jobs:
  - job: Core
    pool:
      vmImage: 'windows-2019'

    steps:
    - task: gittools.gitversion.gitversion-task.GitVersion@4
      displayName: GitVersion
      inputs:
        preferBundledVersion: false

    - task: petersendev.dotnet-global-tool-installer.DotnetGlobalToolInstaller.DotnetGlobalToolInstaller@0
      displayName: 'install housework'
      inputs:
        name: housework

    - script: 'housework author src/*.csproj -s build.ini -r'
      displayName: 'author csproj'

    - task: DotNetCoreCLI@2
      displayName: 'build all'
      inputs:
        projects: src/storage.sln
        arguments: '-c release'

    - task: DotNetCoreCLI@2
      displayName: 'unit tests'
      inputs:
        command: test
        projects: test/Storage.Net.Tests
        arguments: '-c release'

    - task: CopyFiles@2
      displayName: 'copy generated nugets'
      inputs:
        SourceFolder: src
        Contents: '**/*.nupkg'
        TargetFolder: ' $(build.artifactstagingdirectory)'
        CleanTargetFolder: true
        OverWrite: true
        flattenFolders: true

    - task: PublishBuildArtifacts@1
      displayName: 'publish nugets'
      inputs:
        ArtifactName: nuget

  - job: Integration - Other
    pool:
      vmImage: 'windows-2019'

    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Integration Tests (with coverlet)'
      inputs:
        command: test
        projects: ./test/Storage.Net.Test.Integration
        arguments: '--filter Category=Other'

  - job: Integration - Blobs
    pool:
      vmImage: 'windows-2019'

    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Integration Tests (with coverlet)'
      inputs:
        command: test
        projects: ./test/Storage.Net.Test.Integration
        arguments: '--filter Category=Blobs'

        
  - job: Integration - Messages
    pool:
      vmImage: 'windows-2019'

    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Integration Tests (with coverlet)'
      inputs:
        command: test
        projects: ./test/Storage.Net.Test.Integration
        arguments: '--filter Category=Messsages'

        
  - job: Integration - KeyValue
    pool:
      vmImage: 'windows-2019'

    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Integration Tests (with coverlet)'
      inputs:
        command: test
        projects: ./test/Storage.Net.Test.Integration
        arguments: '--filter Category=KeyValue'


- stage: Deploy
  displayName:
  #condition: "eq(variables['Build.SourceBranch'], 'refs/heads/master')"
  condition: "or( eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/v7') )"
  jobs:
  - deployment: NugetOrg
    pool:
      vmImage: 'windows-2019'
    environment: live
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'nuget'
              downloadPath: '$(System.ArtifactsDirectory)'
          - task: NuGetCommand@2
            displayName: nuget.org
            inputs:
              command: push
              packagesToPush: '$(System.ArtifactsDirectory)/nuget/*.nupkg'
              nuGetFeedType: external
              publishFeedCredentials: 'nuget.org (aloneguid)'
